version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#osx--linux--bashonwindows-install-instructions
      - curl -sSL https://install.python-poetry.org | python -
      # Tell poetry to not use a virtual environment
      - $HOME/.local/bin/poetry config virtualenvs.create false
    pre_install:
      # Install project's dependencies
      - $HOME/.local/bin/poetry install --with-docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
