target-version = "py310"  # Pin Ruff to Python 3.10
line-length = 95
output-format = "full"

[lint]
preview = true
select = [
    "B",   # flake8-bugbear
    "E",   # pycodestyle
    "F",   # pyflakes
    "FLY", # flynt
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "W",   # pycodestyle
]
ignore = [
    "E722",  # do not use bare 'except'
    "E741",  # ambiguous variable name
]

[lint.per-file-ignores]
"test/sample-directive-opts.py" = [
    "N999",  # invalid module name
]
"test/sample-directive-special.py" = [
    "N999",  # invalid module name
]

[format]
preview = true
quote-style = "single"
