name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  # We only need to lint once, not for _each_ python version
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Lint
        run: |
          pre-commit run --all-files -v --show-diff-on-failure
          pre-commit gc

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.10'
        - '3.11'
        - '3.12'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check Python version
        run: python --version --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Test with pytest
        run: >
          python -m pytest
          -vv
          --dead-fixtures --dup-fixtures
          --cov . --cov-append --cov-config pyproject.toml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
